# Form implementation generated from reading ui file 'capture_setting.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_capture_setting(object):
    def setupUi(self, capture_setting):
        capture_setting.setObjectName("capture_setting")
        capture_setting.resize(284, 114)
        self.centralwidget = QtWidgets.QWidget(parent=capture_setting)
        self.centralwidget.setObjectName("centralwidget")
        self.capture = QtWidgets.QPushButton(parent=self.centralwidget)
        self.capture.setGeometry(QtCore.QRect(110, 70, 75, 24))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        self.capture.setFont(font)
        self.capture.setObjectName("capture")
        self.angle = QtWidgets.QComboBox(parent=self.centralwidget)
        self.angle.setGeometry(QtCore.QRect(70, 40, 171, 22))
        self.angle.setObjectName("angle")
        self.angle.addItem("")
        self.angle.setItemText(0, "")
        self.angle.addItem("")
        self.angle.addItem("")
        self.angle.addItem("")
        self.angle.addItem("")
        self.angle.addItem("")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 54, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pathfile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pathfile.setGeometry(QtCore.QRect(250, 10, 21, 21))
        self.pathfile.setObjectName("pathfile")
        self.filedisplay = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.filedisplay.setGeometry(QtCore.QRect(70, 10, 171, 21))
        self.filedisplay.setObjectName("filedisplay")
        capture_setting.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=capture_setting)
        self.statusbar.setObjectName("statusbar")
        capture_setting.setStatusBar(self.statusbar)

        self.retranslateUi(capture_setting)
        QtCore.QMetaObject.connectSlotsByName(capture_setting)

    def retranslateUi(self, capture_setting):
        _translate = QtCore.QCoreApplication.translate
        capture_setting.setWindowTitle(_translate("capture_setting", "多通道数据采集"))
        self.capture.setText(_translate("capture_setting", "开始采集"))
        self.angle.setItemText(1, _translate("capture_setting", "90°（2通道）"))
        self.angle.setItemText(2, _translate("capture_setting", "60°（3通道）"))
        self.angle.setItemText(3, _translate("capture_setting", "45°（4通道）"))
        self.angle.setItemText(4, _translate("capture_setting", "30°（6通道）"))
        self.angle.setItemText(5, _translate("capture_setting", "5°（36通道）"))
        self.label.setText(_translate("capture_setting", "保存位置"))
        self.label_2.setText(_translate("capture_setting", "偏振通道"))
        self.pathfile.setText(_translate("capture_setting", "..."))
