# Form implementation generated from reading ui file 'capture_setting111.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Polarization_Setting(object):
    def setupUi(self, Polarization_Setting):
        Polarization_Setting.setObjectName("Polarization_Setting")
        Polarization_Setting.resize(282, 101)
        self.path_display = QtWidgets.QLineEdit(parent=Polarization_Setting)
        self.path_display.setGeometry(QtCore.QRect(70, 10, 171, 21))
        self.path_display.setObjectName("path_display")
        self.path_label = QtWidgets.QLabel(parent=Polarization_Setting)
        self.path_label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.path_label.setFont(font)
        self.path_label.setObjectName("path_label")
        self.angle_label = QtWidgets.QLabel(parent=Polarization_Setting)
        self.angle_label.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.angle_label.setFont(font)
        self.angle_label.setObjectName("angle_label")
        self.angle_display = QtWidgets.QComboBox(parent=Polarization_Setting)
        self.angle_display.setGeometry(QtCore.QRect(70, 40, 171, 22))
        self.angle_display.setObjectName("angle_display")
        self.angle_display.addItem("")
        self.angle_display.setItemText(0, "")
        self.angle_display.addItem("")
        self.angle_display.addItem("")
        self.angle_display.addItem("")
        self.angle_display.addItem("")
        self.angle_display.addItem("")
        self.path_file = QtWidgets.QPushButton(parent=Polarization_Setting)
        self.path_file.setGeometry(QtCore.QRect(250, 10, 21, 21))
        self.path_file.setObjectName("path_file")
        self.download = QtWidgets.QPushButton(parent=Polarization_Setting)
        self.download.setGeometry(QtCore.QRect(110, 70, 75, 24))
        self.download.setObjectName("download")

        self.retranslateUi(Polarization_Setting)
        QtCore.QMetaObject.connectSlotsByName(Polarization_Setting)

    def retranslateUi(self, Polarization_Setting):
        _translate = QtCore.QCoreApplication.translate
        Polarization_Setting.setWindowTitle(_translate("Polarization_Setting", "Form"))
        self.path_label.setText(_translate("Polarization_Setting", "保存位置："))
        self.angle_label.setText(_translate("Polarization_Setting", "偏振通道："))
        self.angle_display.setItemText(1, _translate("Polarization_Setting", "90°（2通道）"))
        self.angle_display.setItemText(2, _translate("Polarization_Setting", "60°（3通道）"))
        self.angle_display.setItemText(3, _translate("Polarization_Setting", "45°（4通道）"))
        self.angle_display.setItemText(4, _translate("Polarization_Setting", "30°（6通道）"))
        self.angle_display.setItemText(5, _translate("Polarization_Setting", "5°（36通道）"))
        self.path_file.setText(_translate("Polarization_Setting", "..."))
        self.download.setText(_translate("Polarization_Setting", "开始采集"))
