# Form implementation generated from reading ui file 'LWIR_NVIDIAui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 392)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.serial_setting_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.serial_setting_button.setGeometry(QtCore.QRect(20, 310, 81, 28))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setBold(True)
        self.serial_setting_button.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./图标/设置.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.serial_setting_button.setIcon(icon)
        self.serial_setting_button.setObjectName("serial_setting_button")
        self.feedback_information = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.feedback_information.setGeometry(QtCore.QRect(420, 190, 251, 151))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(7)
        font.setBold(True)
        self.feedback_information.setFont(font)
        self.feedback_information.setObjectName("feedback_information")
        self.video_base = QtWidgets.QLabel(parent=self.centralwidget)
        self.video_base.setGeometry(QtCore.QRect(20, 20, 381, 281))
        self.video_base.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.video_base.setText("")
        self.video_base.setObjectName("video_base")
        self.video_function = QtWidgets.QLabel(parent=self.centralwidget)
        self.video_function.setGeometry(QtCore.QRect(420, 20, 251, 161))
        self.video_function.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 255); \n"
"}")
        self.video_function.setText("")
        self.video_function.setObjectName("video_function")
        self.function_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.function_name.setGeometry(QtCore.QRect(420, 20, 131, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setBold(True)
        self.function_name.setFont(font)
        self.function_name.setStyleSheet("QLabel {\n"
"    background-color: rgb(204, 224, 254); \n"
"}")
        self.function_name.setObjectName("function_name")
        self.capture_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.capture_button.setGeometry(QtCore.QRect(320, 310, 81, 28))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setBold(True)
        self.capture_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./图标/采集图像.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.capture_button.setIcon(icon1)
        self.capture_button.setObjectName("capture_button")
        self.detection_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.detection_button.setGeometry(QtCore.QRect(220, 310, 81, 28))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setBold(True)
        self.detection_button.setFont(font)
        self.detection_button.setIcon(icon)
        self.detection_button.setObjectName("detection_button")
        self.connect_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(120, 310, 81, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./图标/连接相机.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.connect_button.setIcon(icon2)
        self.connect_button.setObjectName("connect_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serial_setting_button.setText(_translate("MainWindow", "端口设置"))
        self.function_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">时序型目标检测结果</p></body></html>"))
        self.capture_button.setText(_translate("MainWindow", "图像采集"))
        self.detection_button.setText(_translate("MainWindow", "目标检测"))
        self.connect_button.setText(_translate("MainWindow", "打开相机"))
